kind: Secret
apiVersion: v1
metadata:
  name: traefik-forward-auth-secrets
  namespace: kube-system
  labels:
    name: traefik
type: Opaque
data:
  PROVIDERS_GOOGLE_CLIENT_ID:
  PROVIDERS_GOOGLE_CLIENT_SECRET:
  SECRET:
  DDNS:
  URL_PATH:
  WHITELIST:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: forward-auth
  name: forward-auth
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forward-auth
  template:
    metadata:
      labels:
        app: forward-auth
    spec:
      containers:
      - name: traefik-forward-auth
        image: thomseddon/traefik-forward-auth:2
        imagePullPolicy: Always
        env:
        - name: PROVIDERS_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: PROVIDERS_GOOGLE_CLIENT_ID
        - name: PROVIDERS_GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: PROVIDERS_GOOGLE_CLIENT_SECRET
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: SECRET
        - name: COOKIE_DOMAIN
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: DDNS
        - name: AUTH_HOST
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: DDNS
        - name: INSECURE_COOKIE
          value: "false"
        - name: URL_PATH
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: URL_PATH
        - name: WHITELIST
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: WHITELIST
        - name: LOG_LEVEL
          value: debug
        ports:
        - containerPort: 4181
---
apiVersion: v1
kind: Service
metadata:
  name: forward-auth
  namespace: kube-system
  labels:
    app: traefik
spec:
  type: ClusterIP
  selector:
    app: forward-auth
  ports:
  - name: auth-http
    port: 4181
    targetPort: 4181
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-dashboard-forward-auth-mw
  namespace: kube-system
spec:
  forwardAuth:
    address: http://forward-auth.kube-system.svc.cluster.local:4181
    trustForwardHeader: true
    authResponseHeaders:
    - X-Forwarded-User
