ingressClass:
  enabled: true
  isDefaultClass: true
additionalArguments:
- "--certificatesresolvers.${RESOLVER_NAME}.acme.email=${EMAIL}"
- "--certificatesresolvers.${RESOLVER_NAME}.acme.storage=/data/acme.json"
- "--certificatesresolvers.${RESOLVER_NAME}.acme.tlschallenge=true"
ports:
  traefik:
    expose: true
    exposedPort: 9000
    nodePort: 31025
  web:
    nodePort: 31023
  websecure:
    nodePort: 31024
  metrics:
    expose: true
    exposedPort: 9100
    nodePort: 31026
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`${DDNS}`)
    entryPoints: ["websecure"]
    middlewares:
    - name: traefik-dashboard-forward-auth-mw
    tls:
      secretName: ${RESOLVER_NAME}
