apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: airflow-forward-auth-mw
  namespace: airflow
spec:
  forwardAuth:
    address: http://forward-auth.oauth.svc.cluster.local:4181
    trustForwardHeader: true
    authResponseHeaders:
    - X-Forwarded-User
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: airflow-webserver
  namespace: airflow
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`airflow.${DDNS}`)
    kind: Rule
    middlewares:
    - name: airflow-forward-auth-mw
    services:
    - name: airflow-webserver
      port: 8080
  tls:
    certResolver: ${RESOLVER}
