apiVersion: v1
kind: Pod
metadata:
  name: portal-pod
  namespace: portal
  labels:
    app: portal
spec:
  containers:
  - name: portal-container
    image: portal:v1
    ports:
    - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: portal-service
  namespace: portal
spec:
  selector:
    app: portal
  ports:
    - protocol: TCP
      port: 3000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: portal
  namespace: portal
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`${DDNS}`)
    kind: Rule
    services:
    - name: portal-service
      port: 3000
  tls:
    certResolver: ${RESOLVER}